### PR TITLE
Add ACT_EnmityOverlay event source and resources

### PR DESCRIPTION
**Pull request by quisquous**
Sorry for the monster of a commit.

I took the current state of https://github.com/quisquous/ACT_EnmityPlugin and smushed it into OverlayPlugin as an event source.

I did a little bit of opinionated cleanup as I went (sorted by potential contentiousness):
* removed status effects and aggrolist status effect variations, as this requires a release step of downloading images from xivdb and I didn't want to push that pain onto you
* removed some values that didn't seem useful (`Order`, `Level`, `Heading`, `CurrentMP`, `MaxMP`, `CurrentTP`, `MaxTP`)
* consolidated `EffectiveDistance` (a byte from the game, which is rounded to yalms) and `HorizontalDistance` (which ignores z values) in favor of just 3-dimensional `Distance`
* Removed `AnchorTarget` as nobody could figure out what that meant.
* removed some calculated values from C# in favor of vue filters (enmity strings, hp percent)
* removed commented out demo code
* moved all job enums to javascript so it doesn't need a plugin update
* rewrote most of the memory code to be more readable
* fixed quite a few broken memory offsets that apparently nobody cares about

My goal was to have something that was more readable and maintainable.

The biggest design open question for me is this.  There's too much memory to care about to check if anything has changed since the last frame to conditionally send events.  There's a block of ~344 pointers to combatants, each of which is ~7k.  So, this has to be done in a polling fashion.

Previously:
* one thread running at 150ms timer, which refreshed an array of Combatants
* an updater running at a config-specified time which sends events using the (possibly stale) combatant array

Currently:
* an updater running at a config-specified time which builds a combatant array *and* sends needed events

I need to sit down and do a little profiling to see if it's worth keeping around this background thread of combatant refreshing or if it's fine to combine those.  Opinions quite welcome.  Another option is to have two config values, which just seems like more complexity.

I will say that it does also seem like a waste of space to have a second config panel for this event source that only has one option.  Opinions on how to make that better are also welcome.

Finally, please be as picky as you'd like with this code.  I don't have any strong feelings here, and was just trying to make something a bit cleaner than what it started with.  If you want me to try to construct a diff against ACT_EnmityPlugin I can do that too, if that'd be helpful.

### CODE REVIEW

**Comment by ngld** [comment]
I don't think it makes sense to read the memory more often than we send events since we're not going to do anything with that information.

I only have a few nitpicks regarding the code:
* The new enmity overlays have a mix of english and japanese. Can you make a copy of those html files with translated labels (jp to en)?
  I only mention this since it came up once in the ACT discord where someone requested a translated version and it's a fairly simple change.
* I'd rather not have blobs or dependencies (`vue-0.12.7.min.js`) in the repo. Can you remove that file (ideally by modifying the original commit instead of making a new one) and replace it with a CDN-hosted copy (like [this on unpkg.com](https://unpkg.com/vue@0.12.7/dist/vue.min.js) or [this from jsdelivr.net](https://cdn.jsdelivr.net/npm/vue@0.12.7/dist/vue.min.js))?

I want to avoid bloating the repo and I don't think there's a benefit in having a local copy of these files. Finally, we should probably update that Vue version since 0.12.7 is ancient but that's something for later.

Regarding the UI issue: I agree that having a tab just for these options is a waste of space but the same is true for the MiniParseEventSource. I'm not sure if it's feasible to arrange the various event source options in a single table layout or other container though. I'm definitely open to suggestions here.

**Comment by quisquous** [comment]
> I don't think it makes sense to read the memory more often than we send events since we're not going to do anything with that information.

To clarify, I think the intention was that the combatants refresh would run at a lower frequency than the events being sent.

> I only have a few nitpicks regarding the code:
> 
> * The new enmity overlays have a mix of english and japanese. Can you make a copy of those html files with translated labels (jp to en)?

What do you think about a language event and just having the html file handle it?

> * I'd rather not have blobs or dependencies (`vue-0.12.7.min.js`) in the repo. Can you remove that file (ideally by modifying the original commit instead of making a new one) and replace it with a CDN-hosted copy (like [this on unpkg.com](https://unpkg.com/vue@0.12.7/dist/vue.min.js) or [this from jsdelivr.net](https://cdn.jsdelivr.net/npm/vue@0.12.7/dist/vue.min.js))?

Sure, can do.

> Regarding the UI issue: I agree that having a tab just for these options is a waste of space but the same is true for the MiniParseEventSource. I'm not sure if it's feasible to arrange the various event source options in a single table layout or other container though. I'm definitely open to suggestions here.

In the short term, maybe it makes sense to merge it into MiniParseEventSource (although maybe in a different file)?

**Comment by ngld** [comment]
Sorry about the delay. Was busy dealing with support requests and fixing the Cacbot loading issues. At least it looks like everything is working in 0.9.1 now.

> What do you think about a language event and just having the html file handle it?

Sounds like a good idea and with the event callbacks we can even make this reliable. Might want to make it a handler though since I don't think the language ever changes.

> In the short term, maybe it makes sense to merge it into MiniParseEventSource (although maybe in a different file)?

We can make it a partial class (the same way designer files work) and do it that way. I'm not entirely happy with that solution but it works until we find a better one.

**Comment by quisquous** [comment]
Not sure how you like to handle updated pull requests.  I force pushed a rebased/minorly modified original pull request with relevant changes from the original review on top of that separately  in case you wanted to look at those individually.

> * The new enmity overlays have a mix of english and japanese. Can you make a copy of those html files with translated labels (jp to en)?

Now uses the translation handler to change all labels.  There's room for people to translate more if you want, but currently only ja/en.

> * I'd rather not have blobs or dependencies (`vue-0.12.7.min.js`) in the repo. Can you remove that file (ideally by modifying the original commit instead of making a new one) and replace it with a CDN-hosted copy (like [this on unpkg.com](https://unpkg.com/vue@0.12.7/dist/vue.min.js) or [this from jsdelivr.net](https://cdn.jsdelivr.net/npm/vue@0.12.7/dist/vue.min.js))?

Done.  I'll send you another pull request for the jquery you have.

> I want to avoid bloating the repo and I don't think there's a benefit in having a local copy of these files. Finally, we should probably update that Vue version since 0.12.7 is ancient but that's something for later.

Yeah, fair enough.  I just was merging what was there.  :)

> Sorry about the delay. Was busy dealing with support requests and fixing the Cacbot loading issues. At least it looks like everything is working in 0.9.1 now.

No worries at all.  Thank you *SO* much for all of the support you've been doing.  I haven't had a ton of time lately, and I appreciate how much cactbot support you've had to do as well.

> > In the short term, maybe it makes sense to merge it into MiniParseEventSource (although maybe in a different file)?
> 
> We can make it a partial class (the same way designer files work) and do it that way. I'm not entirely happy with that solution but it works until we find a better one.

Done.  It's not the best, because there's some awkward "call the enmity thing" functions, but it's workable.  I left it being called what it was, as I wasn't sure what to name the filename.

I think this is ready for you to take another look.  I did a bunch of testing and things seem to be working.  In the future, if you ever want to manually test that all the memory locations are working correctly, I think `aggrolist.html`, `targetinfo.html`, and one of the `enmity_etc.html` cover everything.  Maybe it'd be good to have a `test.html` in the future.

**Comment by quisquous** [comment]
Also, I haven't done real performance analysis, but things seem to be running fine for me.  I added a field for enmity update rate, but there's no separate timer for combatants.

**Comment by quisquous** [comment]
Oh, one other thing is that I didn't add these new html/js/css files to the visual studio project files.  If you'd like me to do that, I can add that in.

**Comment by ngld** [comment]
I'll take care of adding the new files to the project files. Not much work and you have to also enable to copy flag for it to work correctly. Seems easier to do it myself instead of explaining it (though I guess I just did). \:P

Regarding the `test.html` idea: I think we should make a check for all (easily testable) events. That should make it easier to verify that a new version, game patch or parser update didn't break anything.

That's future stuff though. Thanks for all of your work on this!

**Pull request merged**
