### PR TITLE
Add language event

### PR DESCRIPTION
**Pull request by quisquous**
Subscribing to this sends a one-time event that looks like this:
{ "type": "Language", "language": "English", "languageId": "1" }

### CODE REVIEW

**Comment by quisquous** [comment]
Sorry about the inconsistency in event names.  Some are now `ChangeX` others are `YChanged` and this is now just `Language` on its own (because it's a one time only thing?) Please bikeshed the name as needed.

**Comment by quisquous** [comment]
Oh, sorry, you said in the other pull request that you wanted this to be a handler and not an event.  I'll make that change.

**Comment by quisquous** [comment]
Ok, there we go, it's now a handler.

**Comment by ngld** [comment]
Thanks!

I'm happy with the name now as handler. The other event names are already a mess since we have `CombatData`, `ChangeZone` and similar ones from ACTWS and the new events are named `FileChanged`, `OnlineStatusChanged`, etc.
If Cactbot is registered, you also have a bunch of `on*` events.

I should probably rename the event names copied from ACTWS for consistency. The ACTWS will still use the same event names as before so this won't be an issue for ACTWS compatibility.

**Pull request merged**
