### PR TITLE
Added ObjectStatus and ModelStatus to Combatant

### PR DESCRIPTION
**Pull request by SpaghettiEnjoyer**
Added some useful fields to the Combatant class, and improved upon the aggro list using those fields. I might update/add more statuses in the future as well.

### CODE REVIEW

**Comment by SpaghettiEnjoyer** [comment]
I may have some new findings, will update "shortly".

**Comment by SpaghettiEnjoyer** [comment]
Okay, I'm back. This delay was mostly due to me trying so hard so find something consistent and common that distinguishes the enemies that load into the memory that you're gonna fight later, and those who remain invisible throughout the fight (helpers). 
At the end of the day, I couldn't, but it's not a big of a deal to what I'm trying to create. The stuff that I've added fits my purposes well, and could be used by other people in various ways. Please check the latest commit.

**Comment by ngld** [comment]
This is awesome! Thanks a lot for investigating this and implementing it (you even added extensive documentation ^_^).
Sorry it took me so long to get around to this; I didn't really have to time for FFXIV or OverlayPlugin during the last few months.

**Comment by SpaghettiEnjoyer** [comment]
I'm only just now getting around finishing my overlay so it's all good :) I'll maintain the things that I've added in case there are breaking changes after the expansion hits.

**Pull request merged**
