### PR TITLE
Add overlay resources for target bars

### PR DESCRIPTION
**Pull request by quisquous**
There are four html pages that are all the same, other than a
differently named container.  The JavaScript finds the container by
name to figure out which target bar type it's supposed to be.
Settings for each bar are stored separately, so they can all be
configured differently.

Much of the settings code is cribbed from cactbot.

The settings UI is pretty lackluster looking, but maybe somebody
else could improve it.  Sorry!

Followups here could be including some of the enmity values
(time to death, enmity, relative enmity) as possible options.

### CODE REVIEW

**Comment by quisquous** [comment]
image

**Comment by quisquous** [comment]
I took another look at this and realized that I hadn't added these files to the project or the presets.  I did that and fixed some issues with the example showcase.

**Comment by quisquous** [comment]
The only other followup on my mind is to do a better job with decimal place formatting.  I'm thinking maybe tagging particular types as ints or floats and always give some fixed number of decimal places (2?) on floats.  This would prevent things like Distance going 13.99 => 14 => 14.01.

targetbars is also too big at this point, but it seemed simpler to just have a single file in this case.  Happy to move stuff around if needed.

**Comment by ngld** [comment]
Looks good to me based on a quick glance. I'll test this and let you know if I have more to say. The only nitpick I found so far is that this:
```js
for (const lang in textOptionsAll) {
  options[lang] = {};
  let perLang = textOptionsAll[lang];
  // ...
}
```
would look nicer if written like this:
```js
for (const [lang, perLang] in Object.entries(textOptionsAll)) {
  options[lang] = {};
  // ...
}
```

**Pull request merged**
