### PR TITLE
Make updater resources public

### PR DESCRIPTION
**Pull request by quisquous**
I can still reuse most of these with some string replacements.  <_<

### CODE REVIEW

**Comment by ngld** [comment]
I don't think this is going to work. That file (like all `*.Designer.cs` files) is auto-generated and would be overwritten the next time the `OverlayPlugin.Updater/Resources.resx` file is modified.

**Comment by ngld** [comment]
I can, however, set the resources in the `.resx` file to `public` which does the same and survives a `.resx` change. Now I just have to update `sync_translations.py` to keep the visibility consistent for newly added strings.

**Comment by ngld** [comment]
Turns out the visiblity is a per-file setting which means I don't have to do anything else. \ o /
Fixed in 6cbf4853e69693bb6d8ec1ab321b326fd190c40f

Just, uh, make sure your string replacements work for other languages as well.

**Comment by quisquous** [comment]
Thanks for doing this the right way.  :)

**Pull request closed without merging**
