### PR TITLE
'End ACT encounter' options & Targetbar options CN translations + Targetbar:Add transparent value(a value) to default.

### PR DESCRIPTION
**Pull request by ShadyWhite**

### CODE REVIEW

**Comment by ngld** [comment]
Thanks a lot! Someone else already submitted a PR with CN translations for the targetbar (#144). Both of you chose the same translation for most options but there were a few conflicts. Can you tell me which of the following would be better?

```js
English: 'Size of the border',
Chinese: '边框大小',
Chinese: '描边宽度',

English: 'Color of the border',
Chinese: '边框颜色',
Chinese: '描边颜色',

English: 'Bar color when hp is high',
Chinese: '血条前景色',
Chinese: '血条颜色 - 高血量',

English: 'Percent below where hp is mid',
Chinese: '中血量定义 (剩余体力值百分比)',
Chinese: '定义中血量 (剩余体力值百分比)',

English: 'Bar color when hp is mid',
Chinese: '血条前景色 (中血量)',
Chinese: '血条颜色 - 中血量',

English: 'Percent below where hp is low',
Chinese: '低血量定义 (剩余体力值百分比)',
Chinese: '定义低血量 (剩余体力值百分比)',

English: 'Bar color when hp is low',
Chinese: '血条前景色 (低血量)',
Chinese: '血条颜色 - 低血量',
```

**Comment by ShadyWhite** [comment]
> Thanks a lot! Someone else already submitted a PR with CN translations for the targetbar (#144). Both of you chose the same translation for most options but there were a few conflicts. Can you tell me which of the following would be better?
> 
> ```js
> English: 'Size of the border',
> Chinese: '边框大小',
> Chinese: '描边宽度',
> 
> English: 'Color of the border',
> Chinese: '边框颜色',
> Chinese: '描边颜色',
> 
> English: 'Bar color when hp is high',
> Chinese: '血条前景色',
> Chinese: '血条颜色 - 高血量',
> 
> English: 'Percent below where hp is mid',
> Chinese: '中血量定义 (剩余体力值百分比)',
> Chinese: '定义中血量 (剩余体力值百分比)',
> 
> English: 'Bar color when hp is mid',
> Chinese: '血条前景色 (中血量)',
> Chinese: '血条颜色 - 中血量',
> 
> English: 'Percent below where hp is low',
> Chinese: '低血量定义 (剩余体力值百分比)',
> Chinese: '定义低血量 (剩余体力值百分比)',
> 
> English: 'Bar color when hp is low',
> Chinese: '血条前景色 (低血量)',
> Chinese: '血条颜色 - 低血量',
> ```

English: 'Size of the border',
Chinese: '描边宽度',

English: 'Color of the border',
Chinese: '描边颜色',

English: 'Bar color when hp is high',
Chinese: '血条颜色 - 高血量',

English: 'Percent below where hp is mid',
Chinese: '中血量定义 (剩余体力值百分比)',

English: 'Bar color when hp is mid',
Chinese: '血条颜色 - 中血量',

English: 'Percent below where hp is low',
Chinese: '低血量定义 (剩余体力值百分比)',

English: 'Bar color when hp is low',
Chinese: '血条颜色 - 低血量',

I listed the better translations.

**Comment by ngld** [comment]
Thanks for the quick response!

**Comment by ngld** [comment]
Merged

**Comment by ShadyWhite** [comment]
image
The text here should be "低".
I have made a new PR to resolve it.

**Pull request closed without merging**
